{{- $projectName := include "demo-java-helm.fullname" . -}}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
spec:
  vaultAuthRef: vault-auth
  mount: testbaremetal
  path: tls 
  type: kv-v2 
  destination:
    name: {{ .Values.ingress.tlsSecretName }}
    create: true