apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-java-helm.fullname" . }}
  labels:
    {{- include "demo-java-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: https
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "demo-java-helm.selectorLabels" . | nindent 4 }}
