image:
  repository: registry.integ.dso.minint.fr/testbaremetal/java-demo

ingress:
  enabled: true
  ingressClassName: openshift-default
  host: socleprojecttest.d614.dev.forge.minint.fr
  tlsSecretName: secret-minint
  tls:
    enabled: true

